language: node_js
dist: focal
arch:
  - amd64
node_js:
  - 18
script:
  - yarn run asd
cache: yarn
deploy:
  provider: releases
  token: "$GITHUB_OAUTH_TOKEN"
  file: "README.md"
  skip_cleanup: true
  on:
    tags: true
  draft: true